AF-1450: avoid NPE when empty constructor is invoked
uberfire/uberfire-extensions pull request #325
Opened 2018-08-02 15:23 UTC by porcelli

@ederign  @domhanak fix for the NPE

2018-08-02 17:50 UTC, ederign approved these changes

2018-08-03 05:45 UTC, domhanak approved these changes

2018-08-03 06:23 UTC, domhanak requested changes
@porcelli I am not sure if we can merge it here, imho we need acked prod JIRA

2018-08-03 06:25 UTC, domhanak commented
@mareknovotny Could you please provide some information?

2018-08-04 11:40 UTC, mareknovotny commented
@domhanak we agreed to fix it on JIRA.

2018-08-06 06:32 UTC, domhanak approved these changes

2018-08-06 09:58 UTC, merged